package sync

import (
	"fmt"
	"strings"

	gonaviConnection "opscore/internal/dbmanager/gonavi/connection"
)

// quoteIdent 按方言引用标识符。MySQL 用反引号, PG 族用双引号。
func quoteIdent(name string, d Dialect) string {
	n := strings.ReplaceAll(name, "`", "")
	n = strings.ReplaceAll(n, `"`, "")
	if d == DialectMySQL {
		return "`" + n + "`"
	}
	return `"` + n + `"`
}

// GenerateCreateDDL 从源列/索引定义生成目标方言 CREATE TABLE。
// schema/table 名已由调用方清洗。返回完整 DDL(不带分号)。
func GenerateCreateDDL(schema, table string, columns []gonaviConnection.ColumnDefinition, indexes []gonaviConnection.IndexDefinition, srcDialect, dstDialect Dialect) (string, []string, []string) {
	tn := qualifiedName(schema, table, dstDialect)
	var pkCols []string
	var colDefs []string
	var notes []string
	seenIndex := map[string]bool{}

	for _, col := range columns {
		m := mapColumn(col, srcDialect, dstDialect)
		def := fmt.Sprintf("  %s %s", quoteIdent(col.Name, dstDialect), m.Target)

		// 自增: MySQL AUTO_INCREMENT / PG identity。目标类型非数值时省略自增并提示。
		if m.AutoIncr {
			switch dstDialect {
			case DialectMySQL:
				if !isMySQLIntType(m.Target) {
					notes = append(notes, fmt.Sprintf("列 %s: 自增但目标类型 %s 非整型, 已省略 AUTO_INCREMENT", col.Name, m.Target))
				} else {
					def += " AUTO_INCREMENT"
				}
			case DialectPostgres:
				if !isPGNumericType(m.Target) {
					notes = append(notes, fmt.Sprintf("列 %s: 自增但目标类型 %s 非数值, 已省略 identity", col.Name, m.Target))
				} else {
					def += " GENERATED BY DEFAULT AS IDENTITY"
				}
			}
		} else if m.Default != "" && !isExpressionDefault(m.Default) {
			def += " DEFAULT " + normalizeDefault(m.Default, dstDialect, isBoolType(m.Target))
		}

		if m.IsPK {
			pkCols = append(pkCols, quoteIdent(col.Name, dstDialect))
		}
		colDefs = append(colDefs, def)
	}

	if len(pkCols) > 0 {
		colDefs = append(colDefs, fmt.Sprintf("  PRIMARY KEY (%s)", strings.Join(pkCols, ", ")))
	}

	ddl := fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n%s\n)", tn, strings.Join(colDefs, ",\n"))

	// 二级索引: UNI → UNIQUE INDEX; MUL → INDEX
	var idxDDL []string
	for _, idx := range indexes {
		if seenIndex[idx.Name] || strings.EqualFold(idx.Name, "PRIMARY") {
			continue
		}
		seenIndex[idx.Name] = true
		cn := quoteIdent(idx.ColumnName, dstDialect)
		switch {
		case idx.NonUnique == 0:
			idxDDL = append(idxDDL, fmt.Sprintf("CREATE UNIQUE INDEX IF NOT EXISTS %s ON %s (%s)",
				quoteIdent(idx.Name, dstDialect), tn, cn))
		case dstDialect == DialectMySQL:
			idxDDL = append(idxDDL, fmt.Sprintf("CREATE INDEX %s ON %s (%s)",
				quoteIdent(idx.Name, dstDialect), tn, cn))
		default:
			idxDDL = append(idxDDL, fmt.Sprintf("CREATE INDEX IF NOT EXISTS %s ON %s (%s)",
				quoteIdent(idx.Name, dstDialect), tn, cn))
		}
	}
	return ddl, idxDDL, notes
}

// qualifiedName 带库名的完整表名。
func qualifiedName(schema, table string, d Dialect) string {
	if strings.TrimSpace(schema) == "" {
		return quoteIdent(table, d)
	}
	return quoteIdent(schema, d) + "." + quoteIdent(table, d)
}

func isMySQLIntType(t string) bool {
	base := strings.Fields(t)
	if len(base) == 0 {
		return false
	}
	switch base[0] {
	case "tinyint", "smallint", "mediumint", "int", "integer", "bigint":
		return true
	}
	return false
}

func isPGNumericType(t string) bool {
	base := strings.Fields(t)
	if len(base) == 0 {
		return false
	}
	switch base[0] {
	case "smallint", "integer", "bigint", "numeric", "decimal":
		return true
	}
	return false
}

// isExpressionDefault 判断 DEFAULT 是否为表达式(now() / CURRENT_TIMESTAMP 等), 表达式原样输出。
func isExpressionDefault(d string) bool {
	s := strings.ToLower(strings.TrimSpace(d))
	return strings.ContainsAny(s, "()") ||
		s == "current_timestamp" || s == "now()" || s == "current_date" || s == "current_time" ||
		s == "gen_random_uuid()" || s == "uuid()" ||
		strings.HasPrefix(s, "nextval(") || strings.HasPrefix(s, "autoincrement")
}

func isBoolType(t string) bool {
	base := strings.Fields(t)
	return len(base) > 0 && base[0] == "boolean"
}

// normalizeDefault 规范化字面默认值到目标方言。boolTarget 用于 boolean 列的 0/1 → FALSE/TRUE。
func normalizeDefault(d string, dst Dialect, boolTarget bool) string {
	s := strings.TrimSpace(d)
	lower := strings.ToLower(s)
	switch lower {
	case "null":
		return "NULL"
	case "true":
		if dst == DialectMySQL {
			return "1"
		}
		return "TRUE"
	case "false":
		if dst == DialectMySQL {
			return "0"
		}
		return "FALSE"
	case "current_timestamp", "now()", "now", "current_date", "current_time":
		if dst == DialectMySQL {
			return "CURRENT_TIMESTAMP"
		}
		return "CURRENT_TIMESTAMP"
	}
	// 数字原样; boolean 目标列把 0/1 转为 FALSE/TRUE
	if s == "0" && boolTarget {
		return "FALSE"
	}
	if s == "1" && boolTarget {
		return "TRUE"
	}
	if isNumericLiteral(s) {
		return s
	}
	// 字符串字面量: 统一单引号 + 转义
	if len(s) >= 2 && (s[0] == '\'' || s[0] == '"') {
		s = strings.Trim(s, `"'`)
	}
	return "'" + escapeLiteral(s, dst) + "'"
}

func isNumericLiteral(s string) bool {
	if s == "" {
		return false
	}
	for i, c := range s {
		if (c >= '0' && c <= '9') || c == '.' {
			continue
		}
		if (c == '-' || c == '+') && i == 0 {
			continue
		}
		return false
	}
	return true
}

// escapeLiteral 按目标方言转义字符串字面量内容(不含外层引号)。
func escapeLiteral(s string, dst Dialect) string {
	if dst == DialectMySQL {
		r := strings.NewReplacer(
			`\`, `\\`,
			`'`, `\'`,
			"\n", `\n`,
			"\r", `\r`,
			"\x00", `\0`,
			"\x1a", `\Z`,
		)
		return r.Replace(s)
	}
	return strings.ReplaceAll(s, "'", "''")
}
