package sync

import (
	"strings"
	"testing"

	gonaviConnection "opscore/internal/dbmanager/gonavi/connection"
)

func TestEngineDialect(t *testing.T) {
	for _, e := range []string{"mysql", "mysql_agent", "mariadb", "goldendb"} {
		if EngineDialect(e) != DialectMySQL {
			t.Errorf("%s 应为 mysql 方言", e)
		}
	}
	for _, e := range []string{"postgres", "opengauss", "kingbase", "highgo", "vastbase", "gaussdb"} {
		if EngineDialect(e) != DialectPostgres {
			t.Errorf("%s 应为 postgres 方言", e)
		}
	}
	if EngineDialect("oracle") != "" || EngineDialect("clickhouse") != "" {
		t.Error("未支持引擎应返回空")
	}
}

func TestMapMySQLToPG(t *testing.T) {
	cases := map[string]string{
		"int":                "integer",
		"int unsigned":       "bigint",
		"bigint":             "bigint",
		"bigint unsigned":    "numeric(20,0)",
		"tinyint(1)":         "boolean",
		"varchar(64)":        "varchar(64)",
		"longtext":           "text",
		"blob":               "bytea",
		"datetime":           "timestamp without time zone",
		"datetime(3)":        "timestamp(3) without time zone",
		"timestamp":          "timestamp with time zone",
		"json":               "jsonb",
		"decimal(10,2)":      "numeric(10,2)",
		"double":             "double precision",
		"enum('a','b')":      "varchar(255)",
	}
	for src, want := range cases {
		got, _ := mapMySQLToPG(parseTypeName(src))
		if got != want {
			t.Errorf("mapMySQLToPG(%s) = %s, want %s", src, got, want)
		}
	}
}

func TestMapPGToMySQL(t *testing.T) {
	cases := map[string]string{
		"integer":            "int",
		"bigint":             "bigint",
		"boolean":            "tinyint(1)",
		"character varying(32)": "varchar(32)",
		"text":               "text",
		"bytea":              "blob",
		"timestamptz":        "datetime(6)",
		"timestamp with time zone": "datetime(6)",
		"jsonb":              "json",
		"uuid":               "char(36)",
		"numeric(12,4)":      "decimal(12,4)",
		"serial":             "text", // serial 不是基础类型, 落默认(由 AutoIncr 语义处理)
	}
	for src, want := range cases {
		got, _ := mapPGToMySQL(parseTypeName(src))
		if got != want {
			t.Errorf("mapPGToMySQL(%s) = %s, want %s", src, got, want)
		}
	}
}

func TestGenerateCreateDDLMySQLToPG(t *testing.T) {
	cols := []gonaviConnection.ColumnDefinition{
		{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
		{Name: "name", Type: "varchar(64)", Nullable: "NO"},
		{Name: "score", Type: "decimal(10,2)", Nullable: "YES"},
		{Name: "del", Type: "tinyint(1)", Nullable: "NO", Default: strPtr("0")},
		{Name: "attrs", Type: "json", Nullable: "YES"},
	}
	idx := []gonaviConnection.IndexDefinition{
		{Name: "PRIMARY", ColumnName: "id", NonUnique: 0, SeqInIndex: 1},
		{Name: "idx_name", ColumnName: "name", NonUnique: 1, SeqInIndex: 1},
	}
	ddl, idxDDL, _ := GenerateCreateDDL("targetdb", "users", cols, idx, DialectMySQL, DialectPostgres)
	for _, want := range []string{
		`"targetdb"."users"`,
		`"id" bigint GENERATED BY DEFAULT AS IDENTITY`,
		`"name" varchar(64) NOT NULL`,
		`"score" numeric(10,2)`,
		`"del" boolean NOT NULL DEFAULT FALSE`,
		`"attrs" jsonb`,
		`PRIMARY KEY ("id")`,
	} {
		if !strings.Contains(ddl, want) {
			t.Errorf("DDL 缺少 %q:\n%s", want, ddl)
		}
	}
	if len(idxDDL) != 1 || !strings.Contains(idxDDL[0], `CREATE INDEX IF NOT EXISTS "idx_name"`) {
		t.Errorf("索引 DDL 不符: %v", idxDDL)
	}
}

func TestGenerateCreateDDLPGToMySQL(t *testing.T) {
	cols := []gonaviConnection.ColumnDefinition{
		{Name: "id", Type: "integer", Nullable: "NO", Key: "PRI", Extra: "nextval('users_id_seq')"},
		{Name: "flag", Type: "boolean", Nullable: "NO", Default: strPtr("true")},
		{Name: "payload", Type: "jsonb", Nullable: "YES"},
	}
	ddl, _, _ := GenerateCreateDDL("targetdb", "t", cols, nil, DialectPostgres, DialectMySQL)
	for _, want := range []string{
		"`targetdb`.`t`",
		"`id` int AUTO_INCREMENT",
		"`flag` tinyint(1) NOT NULL DEFAULT 1",
		"`payload` json",
		"PRIMARY KEY (`id`)",
	} {
		if !strings.Contains(ddl, want) {
			t.Errorf("DDL 缺少 %q:\n%s", want, ddl)
		}
	}
}

func TestQuoteValue(t *testing.T) {
	if quoteValue(nil, DialectMySQL, "") != "NULL" {
		t.Error("nil 应为 NULL")
	}
	if quoteValue(true, DialectMySQL, "") != "1" || quoteValue(true, DialectPostgres, "") != "TRUE" {
		t.Error("bool 方言不符")
	}
	if got := quoteValue(`he said "hi" \ 'x'`, DialectMySQL, ""); got != `'he said "hi" \\ \'x\''` {
		t.Errorf("MySQL 转义不符: %s", got)
	}
	if got := quoteValue(`it's`, DialectPostgres, ""); got != `'it''s'` {
		t.Errorf("PG 转义不符: %s", got)
	}
	if got := quoteValue([]byte{0xDE, 0xAD}, DialectMySQL, "blob"); got != "X'dead'" {
		t.Errorf("MySQL bytea 不符: %s", got)
	}
	if got := quoteValue([]byte{0xDE, 0xAD}, DialectPostgres, "bytea"); got != `'\xdead'` {
		t.Errorf("PG bytea 不符: %s", got)
	}
	// boolean 目标列收到数字/字符串(驱动归一化后)
	if quoteValue(int64(1), DialectPostgres, "boolean") != "TRUE" || quoteValue(int64(0), DialectPostgres, "boolean") != "FALSE" {
		t.Error("int→boolean 不符")
	}
	if quoteValue("1", DialectPostgres, "boolean") != "TRUE" || quoteValue("0", DialectPostgres, "boolean") != "FALSE" {
		t.Error("string→boolean 不符")
	}
	// bytea 目标列收到 GoNavi 归一化的 "0x<hex>" 字符串
	if got := quoteValue("0xdead", DialectPostgres, "bytea"); got != `'\xdead'` {
		t.Errorf("string→bytea 不符: %s", got)
	}
	if got := quoteValue("0xdead", DialectMySQL, "blob"); got != "X'dead'" {
		t.Errorf("0x→MySQL blob 不符: %s", got)
	}
}

func TestBuildInsertSQL(t *testing.T) {
	sqlText := buildInsertSQL("db", "t", []string{"a", "b"}, map[string]string{"a": "integer", "b": "varchar"}, [][]any{{1, `x'y`}, {nil, int64(2)}}, DialectMySQL, 0)
	want := "INSERT INTO `db`.`t` (`a`, `b`) VALUES (1,'x\\'y'),\n(NULL,2)"
	if sqlText != want {
		t.Errorf("INSERT SQL 不符:\n got: %s\nwant: %s", sqlText, want)
	}
	// 列序与 colBases 按名字对齐: 流式列序乱序时 boolean/bytea 仍正确
	sqlText2 := buildInsertSQL("db", "t", []string{"flag", "data"}, map[string]string{"flag": "boolean", "data": "bytea"},
		[][]any{{int64(1), "0xdeadbeef"}}, DialectPostgres, 0)
	if !strings.Contains(sqlText2, "TRUE") || !strings.Contains(sqlText2, `'\xdeadbeef'`) {
		t.Errorf("乱序列对齐失败: %s", sqlText2)
	}
	// RFC3339 时间归一
	if got := quoteValue("2024-05-01T10:00:00+08:00", DialectPostgres, "timestamp"); got != "'2024-05-01 10:00:00'" {
		t.Errorf("RFC3339 归一不符: %s", got)
	}
}

func TestDetectIncremental(t *testing.T) {
	cols := []gonaviConnection.ColumnDefinition{
		{Name: "id", Type: "bigint", Key: "PRI", Extra: "auto_increment"},
		{Name: "updated_at", Type: "datetime"},
	}
	if c, s := detectIncremental(cols, ""); c != "id" || s != IncrAutoIncrement {
		t.Errorf("应探测自增主键: %s %s", c, s)
	}
	if c, s := detectIncremental(cols, "updated_at"); c != "updated_at" || s != IncrTimestamp {
		t.Errorf("应优先指定列: %s %s", c, s)
	}
	noIncr := []gonaviConnection.ColumnDefinition{{Name: "name", Type: "varchar(32)"}}
	if _, s := detectIncremental(noIncr, ""); s != IncrNone {
		t.Error("无增量列应返回 none")
	}
}

func strPtr(s string) *string { return &s }
